apiVersion: v1
kind: Service
metadata: 
  name: webapp-service
spec: 
  selector: 
    app: webapp-pod
  ports:
    - name: web
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: webapp-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
      - name: webapp-pod
        image: pahud/greeting:latest
        ports:
        - containerPort: 8080
